language: c

env:
        global:
                - HUB_USER=yomimono
                - DISTRO=debian-9
                - PACKAGE=ocaml-test-x509
                - INSTALL=false
                - PINS="bun:https://github.com/yomimono/ocaml-bun.git"
                - OPAMYES=true #workaround an `opam depext -ui`
        matrix:
                # docker hub (the ultimate source of the base images) doesn't allow + in names, hence the _
                - OCAML_VERSION=4.06.0_afl

before_install:
- sudo sysctl kernel.core_pattern=core

install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/depext-y/.travis-docker.sh

script: bash -ex .travis-docker.sh
